# Generated by Django 4.1.5 on 2023-01-13 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="division",
            options={"ordering": ["div_nr"]},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["div", "points"]},
        ),
        migrations.RenameField(
            model_name="player",
            old_name="firstname",
            new_name="first",
        ),
        migrations.RenameField(
            model_name="player",
            old_name="lastname",
            new_name="last",
        ),
        migrations.RenameField(
            model_name="team",
            old_name="division",
            new_name="div",
        ),
        migrations.RemoveField(
            model_name="division",
            name="division_number",
        ),
        migrations.RemoveField(
            model_name="team",
            name="first_player",
        ),
        migrations.RemoveField(
            model_name="team",
            name="team_name",
        ),
        migrations.AddField(
            model_name="division",
            name="div_nr",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name="team",
            name="p1",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="first_player",
                to="league.player",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="p2",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="second_player",
                to="league.player",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="email",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
