# Generated by Django 4.1.5 on 2023-01-13 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0002_alter_division_options_alter_team_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="p1",
            field=models.OneToOneField(
                default=-2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="first_player",
                to="league.player",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="p2",
            field=models.OneToOneField(
                blank=True,
                default=-1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="second_player",
                to="league.player",
            ),
        ),
    ]
