# Generated by Django 4.1.5 on 2023-01-13 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0003_alter_team_p1_alter_team_p2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="div",
            field=models.ForeignKey(
                default=-1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="league.division",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="p1",
            field=models.OneToOneField(
                default=-2,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="first_player",
                to="league.player",
            ),
        ),
    ]
